export const titles = ['BUSINESS', 'WEBDESIGN/CODING', 'SPORTS', 'FREE TIME']

export const description = [
    'What I like about Business is that it can be as complex as you want it to be. It gives you a sense of freedom, to develop something out of nothing. During school I took courses like: business strategies, marketing, finance, management and communication. These courses have given me a good inside how businesses work. I also love to read different business-related newspapers like: Wall Street Journal, Economist and Reuters.',
    'I have experience in coding: HTML, CSS and JavaScript. These are all web languages and used to create websites. Besides that, I do know how to work with different frameworks like Bootstrap 4 and Angular. I am starting to learn myself other coding languages like Python and SQL. What I like about coding is that a big part of coding is problem solving and makes you think in a way nothing else does!',
    'I believe that a happy life starts with a physical and mentally balanced life. This is one of the reasons why I always have been practicing sports. When I was young I started off with Judo, then went to play soccer and right now I love to Run and Workout. Sport for me is taking a moment for myself, to reflect about my days, life, career, and goals.',
    'In my free time I like to read books, go out with friend or watch a movie. Most of the books I read are about: Business, management, finance, biographies, philosophy and technologies like; Artificial intelligence, machine learning, blockchain, big data, etc. Reading gives me a good inside on how people think, and it is a way of extracting knowledge from someone else.'
]

export const moreAboutMe =
    'I grew up in Eindhoven and lived there till I was 19 years old. Eindhoven is one of the bigger cities in The Netherlands and has a lot to offer. My dad has his own eCommerce business, he works from home, so he was always available for me and my brother. \n My dad owns a sailboat so when I was younger my parents took me and my brother, during the vacations and weekend, on sailing trips at the coast of The Netherlands. One time, we crossed the English Channel to go to England and spent some time there. I do remember a lot of that vacation, it was fantastic! I have always been an outdoor kid, loved to play soccer or other outdoor games with the neighbor kids. This brought me some good, reliable friend in Eindhoven! \nI do have an entrepreneurial mindset. I love to explore, try, learn and make things happen. When I was young, I bought one of the first NXT robots that I could program to do specific tasks. When I was 14, I explored technologies like Blockchain, trying to “mine” Bitcoin on my PC (unsuccessful unfortunately). I bought a good amount of cryptocurrency when I was 17 and spent most of the profits on my education in the US, everything in the US was self-financed. I have always been a very independent person, financially and in life itself. \nTo keep on top of news topics and current developments in the business world, I like to read the Wall Street Journal, the Economist, and Reuters on a daily basis. I am continuously expanding my knowledge on a brought field of subjects and trying to develop myself as a person. \nOutside school or work, I like to travel. My parents took me and my brother every year on vacations anywhere in Europe. I have seen most of the European countries! My last travel trip (on my own), was a road trip through the west and east coast of the United States and Canada. I just love to learn about other cultures and people!'
